image: ubuntu:18.04

variables:
  BIN_NAME: main.out
  TEST_LOG: test.log

before_script:
  - apt-get -y update

stages:
  - build
  - test
  - pages

build:
  stage: build
  script:
    - apt-get -y install gcc g++
    - g++ -o ${BIN_NAME} main.cpp
  artifacts:
    paths:
      - ${BIN_NAME}

test:
  stage: test
  script:
    - ./${BIN_NAME} > ${TEST_LOG}
    - diff test.sample ${TEST_LOG}

pages:
  stage: pages
  script:
    - apt-get -y install doxygen
    - apt-get -y install graphviz
    - doxygen Doxyfile.cfg
    - mv doc/html/ public/
  artifacts:
    paths:
    - public
  only:
  - master
